### ISSUE TITLE
QoSProfile is hardcoded

### ISSUE THREAD

**Issue by Timple** [felixdivo/ros2-easy-test#31]
Transient local topics cannot be send nor received because the `DurabilityPolicy` cannot be set to `TRANSIENT_LOCAL`

**Comment by Timple** [comment]
Awesome, thank you both for the effort!

Happily awaiting a new release :slightly_smiling_face:

**Comment by felixdivo** [comment]
> Happily awaiting a new release 🙂

Me too. I want to complete #33 & possibly #27 before doing so, but it's on the list for this week. :)
