### ISSUE TITLE
`makefun` not listed as dependency

### ISSUE THREAD

**Issue by Timple** [felixdivo/ros2-easy-test#40]
If should be part of the `exec_depend` in the package.xml.

And an entry should be added to the rosdistro https://github.com/ros/rosdistro/blob/80576121cd588793659f626976c813dca4a9c301/rosdep/python.yaml#L6844

But since this dependency is only used for a 5 line function:

```python
def remove_signature_parameters(s, param_names):
    """
    Removes the provided parameters from the signature `s` (returns a new `Signature` instance).

    :param s:
    :param param_names: a list of parameter names to remove
    """
    params = OrderedDict(s.parameters.items())
    for param_name in param_names:
        del params[param_name]
    return s.replace(parameters=params.values())
```

It might also just be rephrased here depending on preference.

**Comment by felixdivo** [comment]
Jupp, that was still missing for #23. It is now done in #41.
